version: '3.1'
services:

  limesurvey:
    image: acspri/limesurvey:latest
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: example
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
    volumes:
      # Installed LimeSurvey plugins
      - ./plugins:/var/www/html/plugins
      # New or created themes, Survey resources, Data from uploaded responses
      - ./upload:/var/www/html/upload
      # Configuration and security.php for encrypted responses
      - ./config:/var/www/html/application/config

  mysql:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
